"""Stub file for custom_components/reflex_mermaidjs/mermaidjs.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal, TypedDict

import reflex as rx
from reflex.components.component import NoSSRComponent
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex_components_core.core.breakpoints import Breakpoints

_JSX_ASSET = rx.asset("mermaid_diagram.jsx", shared=True)

class RenderEvent(TypedDict):
    svg: str
    diagram_type: str
    render_id: str
    render_ms: int

class ErrorEvent(TypedDict):
    message: str
    line: int | None
    expected: list[str] | None

class NodeClickEvent(TypedDict):
    node_id: str
    callback: str | None
    label: str | None
    args: list[Any]

class ZoomEvent(TypedDict):
    zoom: float
    x: float
    y: float

class IconPack(TypedDict, total=False):
    name: str
    url: str
    pack: str

class Mermaid(NoSSRComponent):
    @classmethod
    def create(
        cls,
        *children,
        chart: Var[str] | str | None = None,
        config: Var[dict[str, Any]] | dict[str, Any] | None = None,
        theme: Literal[
            "base",
            "dark",
            "default",
            "forest",
            "neo",
            "neo-dark",
            "neutral",
            "null",
            "redux",
            "redux-color",
            "redux-dark",
            "redux-dark-color",
        ]
        | Var[
            Literal[
                "base",
                "dark",
                "default",
                "forest",
                "neo",
                "neo-dark",
                "neutral",
                "null",
                "redux",
                "redux-color",
                "redux-dark",
                "redux-dark-color",
            ]
        ]
        | None = None,
        look: Literal["classic", "handDrawn", "neo"]
        | Var[Literal["classic", "handDrawn", "neo"]]
        | None = None,
        layout: Var[str] | str | None = None,
        security_level: Literal["antiscript", "loose", "sandbox", "strict"]
        | Var[Literal["antiscript", "loose", "sandbox", "strict"]]
        | None = None,
        font_family: Var[str] | str | None = None,
        font_size: Var[int] | int | None = None,
        hand_drawn_seed: Var[int] | int | None = None,
        dark_mode: Var[bool] | bool | None = None,
        html_labels: Var[bool] | bool | None = None,
        max_text_size: Var[int] | int | None = None,
        max_edges: Var[int] | int | None = None,
        wrap: Var[bool] | bool | None = None,
        deterministic_ids: Var[bool] | bool | None = None,
        log_level: Literal["debug", "error", "fatal", "info", "trace", "warn"]
        | Var[Literal["debug", "error", "fatal", "info", "trace", "warn"]]
        | None = None,
        theme_variables: Var[dict[str, Any]] | dict[str, Any] | None = None,
        theme_css: Var[str] | str | None = None,
        appearance: Literal["dark", "light"] | Var[Literal["dark", "light"]] | None = None,
        tidy_tree: Var[bool] | bool | None = None,
        zenuml: Var[bool] | bool | None = None,
        font_awesome: Var[bool] | bool | None = None,
        icon_packs: Var[list[IconPack | str]] | list[IconPack | str] | None = None,
        debounce: Var[int] | int | None = None,
        pan_zoom: Var[bool] | bool | None = None,
        show_controls: Var[bool] | bool | None = None,
        controls_position: Literal["bottom-left", "bottom-right", "top-left", "top-right"]
        | Var[Literal["bottom-left", "bottom-right", "top-left", "top-right"]]
        | None = None,
        min_zoom: Var[float] | float | None = None,
        max_zoom: Var[float] | float | None = None,
        zoom_step: Var[float] | float | None = None,
        fit_on_render: Literal["auto"] | Var[Literal["auto"] | bool] | bool | None = None,
        max_fit_zoom: Var[float] | float | None = None,
        grid: Var[bool] | bool | None = None,
        center: Var[bool] | bool | None = None,
        error_mode: Literal["inline", "keep-last", "none"]
        | Var[Literal["inline", "keep-last", "none"]]
        | None = None,
        click_callbacks: Var[list[str]] | list[str] | None = None,
        node_click: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_error: EventType[()] | EventType[ErrorEvent] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_node_click: EventType[()] | EventType[NodeClickEvent] | None = None,
        on_render: EventType[()] | EventType[RenderEvent] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        on_zoom_change: EventType[()] | EventType[ZoomEvent] | None = None,
        **props,
    ) -> Mermaid:
        """Create a mermaid diagram.

        The diagram text can be passed positionally or with ``chart=``.

        Args:
            *children: Optionally, the diagram text (str or string Var).
            chart: ----------------------------------------------------------------- content The mermaid diagram definition (may include YAML front matter).
            config: ----------------------------------------------------------- mermaid config Raw MermaidConfig passed to ``mermaid.initialize`` (dedicated props win).
            theme: Theme: default, base, dark, forest, neutral, neo, neo-dark, redux, ...
            look: Look: classic, handDrawn or neo.
            layout: Layout algorithm: dagre, elk, elk.stress, tidy-tree, ...
            security_level: Level of trust for the diagram source. ``loose`` enables click callbacks.
            font_family: Font family used by the diagrams.
            font_size: Base font size.
            hand_drawn_seed: Seed used by the handDrawn look (0 = random).
            dark_mode: Tell themes to compute colors for a dark background.
            html_labels: Render labels as HTML (foreignObject) instead of SVG text.
            max_text_size: Maximum diagram text length.
            max_edges: Maximum number of edges.
            wrap: Wrap long labels automatically.
            deterministic_ids: Generate deterministic ids (useful for snapshot tests).
            log_level: mermaid log level.
            theme_variables: Theme variables (most useful with ``theme="base"``).
            theme_css: Extra CSS injected in the generated SVG.
            appearance: When no theme is set, "dark" picks the dark variant of each diagram type's default theme (like mermaid.live).
            tidy_tree: ------------------------------------------------------------------ plugins Register the tidy-tree layout (``layout: tidy-tree``).
            zenuml: Register the ZenUML diagram eagerly (it is also auto-enabled when the text starts with ``zenuml``).
            font_awesome: Load Font Awesome CSS so ``fa:fa-car`` icons render.
            icon_packs: Iconify packs: names (``logos`` and ``mdi`` are bundled, others load from jsDelivr) or ``{"name": ..., "url": ...}`` dicts.
            debounce: ------------------------------------------------------------- behaviour/UI Debounce re-renders (ms) when the chart text changes quickly.
            pan_zoom: Enable mouse-wheel zoom and drag-to-pan. The component then fills its box: give it a height.
            show_controls: Show the floating zoom toolbar (defaults to ``pan_zoom``).
            controls_position: Toolbar position.
            min_zoom: Minimum zoom factor.
            max_zoom: Maximum zoom factor.
            zoom_step: Relative zoom step used by the toolbar buttons.
            fit_on_render: Pan & zoom mode: True fits after every render, False only on the first one, "auto" (default) also refits when the diagram type or size changes a lot.
            max_fit_zoom: Largest zoom factor "fit" may use (1 = never enlarge small diagrams).
            grid: Draw a dotted grid behind the diagram.
            center: Center the SVG horizontally (static mode).
            error_mode: inline: show errors; keep-last: show errors and keep the last good SVG; none: hide errors.
            click_callbacks: Names used in ``click nodeId callbackName`` directives, routed to ``on_node_click``.
            node_click: Emit ``on_node_click`` for clicks on any node, even without ``click`` directives.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_render: ------------------------------------------------------------------- events Fired after a successful render.
            on_error: Fired when the diagram cannot be parsed or rendered.
            on_node_click: Fired when a node is clicked (see ``node_click`` and ``click_callbacks``).
            on_zoom_change: Fired when the zoom or pan position changes.
            **props: Component props.

        Returns:
            The component.
        """
        ...

mermaid = Mermaid.create
